version: "3.7"

services:

  mariadb:
    container_name: maria-db-dev
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <INPUT YOUR PASSWORD>

  phpmyadmin:
    container_name: phpmyadmin-dev
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
  mongo:
    container_name: mongo-dev
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=<INPUT YOUR PASSWORD>
    networks: 
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes: 
      - mongodb-data:/data/db
    restart: always
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    networks: 
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=<INPUT YOUR PASSWORD>
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=<INPUT YOUR PASSWORD>
    ports:
      - '8081:8081'
    volumes: 
      - mongodb-data:/data/mongo-express      

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mariadb-data:
  mongodb-data: